name: dashboard
channels:
  - conda-forge
dependencies:
  - blpapi=3.17.1=py37_blpapicpp3.16.1.1_0
  - pip
  - pip:
    - cmake
    - pdblp==0.1.8
    - streamlit
    - Cython
    - pyarrow==0.9.0
    

prefix: C:\Users\javedm\Anaconda3\envs\dashboard
